#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m[" | pv -qL 10
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo ""
echo "  REINICIANDO SLOWDNS..."
echo ""
fun_restart () {
screen -ls | grep slowdns | cut -d. -f1 | awk '{print $1}' | xargs kill
sleep 3
nameserver='1234'
cd /root
screen -dmS slowdns ./dns-server -udp :5300 -privkey-file server.key $nameserver 127.0.0.1:22
}
sleep 2
fun_bar 'fun_restart'
echo ""
echo "  SlowDNS Reiniciado Com Sucesso! [✔]"
