#!/bin/bash
clear
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "INSTALANDO SLOWDNS SSH" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "By @Laael"
echo ""
echo -e "ATUALIZANDO LISTA DE PACOTES..."
fun_att () {
apt update && apt upgrade -y
}
fun_att
echo -e "INSTALANDO E ATUALIZANDO PACOTES NECESSARIOS..."
install_pkgs () {
apt install screen -y 
apt install cron -y 
apt install iptables -y 
service cron reload
service cron restart
service iptables reload
service iptables restart
}
install_pkgs
echo -e "BAIXANDO BINARIO DNSTT..."
download_dnstt () {
cd /root && wget https://github.com/LaelsonCG/slowdns/raw/main/dns-server
chmod +x dns-server
}
download_dnstt
echo -e "CONFIGURANDO IPTABLES..."
ipt_set(){
cd /etc 
rm -rf rc.local
wget https://github.com/LaelsonCG/slowdns/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
ipt_set
clear
echo ""
echo -e "\033[1;31m ATENCAO \033[1;33m!!!"
echo ""
echo -ne "\033[1;32m INFORME SEU NS (NAMESERVER)\033[1;37m: "; read nameserver
cd /root
touch infons
echo $nameserver >> infons
sleep 1
wget http://downloads.onehostbr.xyz/files/dns-server/startdns 
wget http://downloads.onehostbr.xyz/files/dns-server/restartdns 
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /root/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /root/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
clear
echo -e "FINALIZANDO..."
finish_ist() {
cd /root
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
FILE=/root/server.key
FILE2=/root/server.pub
if [[ -f FILE ]] && [[ -f FILE2 ]]
then
   echo -e "RESTAURANDO KEY...."
else 
  echo -e "GERANDO KEY...."
    ./dns-server -gen-key -privkey-file server.key -pubkey-file server.pub
fi

./startdns
}
finish_ist
clear
echo ""
echo -e "\033[1;31m FINALIZADO!\033[1;33m!!!"
echo ""
echo "SUA KEY: " && cat /root/server.pub 
echo "SEU NS: " && cat /root/infons
echo ""
echo "SUA KEY está salva no arquivo /root/server.pub" 
echo ""
echo "PARA REINICIAR O SLOWDNS,BASTA RODAR O COMANDO restartdns" 
echo ""
echo "SALVE OS ARQUIVOS server.pub e server.key em /root/ num local seguro" 
echo "Caso troque de VPS,apenas coloque os arquivos server.pub e server.key em /root/ e rode esse script novamente" 
echo "Assim não precisaremos trocar de keys ao mudar de servidor" 
