#!/bin/bash
clear
echo -e "\033[0;36m#===================================================#\033[m"
echo -e "\033[0;36m# .|'''.|'||                '||''|. '|.   '|'.|'''.|#\033[m"
echo -e "\033[0;36m# ||..  ' ||  ... ... ... ...||   || |'|   | ||..  '#\033[m"
echo -e "\033[0;36m#  ''|||. ||.|  '|.||  ||  | ||    ||| '|. |  ''|||.#\033[m"
echo -e "\033[0;36m#.     '||||||   || ||| |||  ||    |||   |||.     '|#\033[m"
echo -e "\033[0;36m#|'....|'.||.'|..|'  |   |  .||...|'.|.   '||'....|'#\033[m"
echo -e "\033[0;36m#---------------------------------------------------#\033[m"
echo -e "\033[0;36m#\033[m \033[0;31mDESENVOLVIDO POR @LAAEL | CANAL @OFICIAL_SPEEDNET\033[m \033[0;36m#\033[m"
echo -e "\033[0;36m#===================================================#\033[m"
PS3='O que deseja fazer?: ' 
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "MENU SLOWDNS MANAGER V2.0" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
options=("Instalar SlowDNS SSH" "Instalar SlowDNS SSL" "Reiniciar SlowDNS" "Parar SlowDNS" "Atualizar SlowDNS" "Remover SlowDNS" "Remover SlowDNS e Menu" "Sair")
select opt in "${options[@]}"
do
    case $opt in
        "Instalar SlowDNS SSH")
            rm -rf dns-server; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/ssh/slowdns-install; chmod +x slowdns-install; ./slowdns-install
            slowdns
            ;;
        "Instalar SlowDNS SSL")
            rm -rf dns-server; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/ssl/slowdns-install; chmod +x slowdns-install; ./slowdns-install
            slowdns
            ;;
        "Reiniciar SlowDNS")
            restartdns
            slowdns
            ;;
        "Parar SlowDNS")
            desabledns
            slowdns
            ;;
        "Atualizar SlowDNS")
            apt update; apt upgrade -y; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/updatedns; chmod +x updatedns; ./updatedns
            slowdns
            ;;
        "Remover SlowDNS")
            wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/remove-slow; chmod +x remove-slow; ./remove-slow
            slowdns
            ;;
        "Remover SlowDNS e Menu")
            wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/remove-slow; chmod +x remove-slow; ./remove-slow; rm /bin/slowdns
            break
            ;;
        "Sair")
            clear
            break
            ;;
        *) echo -e "Opção inválida! $REPLY"
            ;;
    esac
done
