#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m[" | pv -qL 15
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo ""
echo -e "   \033[0;36mATUALIZANDO SLOWDNS.../033[0m"
echo ""
fun_update () {
rm -rf remove-slow; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/remove-slow; chmod +x remove-slow; ./remove-slow
rm -rf /bin/slowdns && rm; /root/remove-slow
rm -rf dnstt-install; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/dnstt-install; chmod +x dnstt-install; ./dnstt-install
}
fun_bar 'fun_update'
echo -e "\033[0;36mSLOWDNS ATUALIZADO COM SUCESSO! [✔]/033[0m"
sleep 2
