#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
clear
echo -e "\033[1;33mATENÇÃO AQUI POR FAVOR!\033[0m"
echo ""
echo -e "Ao fim do processo será necessário configurar"
echo -e "novamente o serviço de SlowDNS, escolha a opção"
echo -e "Usar key atual para restaurar sua antiga key"
echo ""
read -p "Pressione [ENTER] para continuar ou CTRL + C para cancelar"
echo ""
echo -e "   \033[0;36mREMOVENDO ARQUIVOS ANTIGOS...\033[0m"
echo ""
fun_remove () {
rm -rf remove-slow; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/remove-slow; chmod +x remove-slow; ./remove-slow
rm -rf /bin/slowdns && rm /root/remove-slow
sleep 2
}
fun_bar 'fun_remove'
rm -rf install; wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/install && chmod +x install && bash install
sleep 5
echo -e "\033[0;36mSLOWDNS ATUALIZADO COM SUCESSO! [✔]\033[0m"
echo ""
read -p "Tecle [ ENTER ] para finalizar esta tarefa"
rm update
