#!/bin/bash
screen -ls | grep slowdns | cut -d. -f1 | awk '{print $1}' | xargs kill
nameserver='1234'
cd /root
screen -dmS slowdns ./dns-server -udp :5300 -privkey-file server.key $nameserver 127.0.0.1:443
