#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m[" | pv -qL 10
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "INSTALANDO SLOWDNS SSL" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      Esse script irá fazer a instalação do"
echo -e "     slowdns para tunelamento de DNS com SSL."
echo -e ""
echo -e "         \033[1;33mInstalador feito por @Laael ❤️ \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "ATUALIZANDO LISTA DE PACOTES..." | pv -qL 10
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "INSTALANDO E ATUALIZANDO PACOTES NECESSARIOS..." | pv -qL 10
install_pkgs () {
apt install screen -y 
apt install cron -y 
apt install iptables -y 
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "BAIXANDO BINARIO DNSTT..."
download_dnstt () {
cd /root && wget https://github.com/LaelsonCG/slowdns/raw/main/dns-server
chmod +x dns-server
}
fun_bar 'download_dnstt'
echo -e "CONFIGURANDO IPTABLES..." | pv -qL 10
ipt_set () {
cd /etc 
rm -rf rc.local
wget https://github.com/LaelsonCG/slowdns/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATENÇÃO NESSA ETAPA! \033[1;33m!!!"
echo ""
echo -ne "\033[1;32m INFORME SEU NS (NAMESERVER)\033[1;37m: " | pv -qL 10; read nameserver
cd /root
touch infons
echo $nameserver >> infons
sleep 1
wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/drop/startdns 
wget https://raw.githubusercontent.com/LaelsonCG/slowdns/main/drop/restartdns 
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /root/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /root/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
clear
echo -e "FINALIZANDO..." | pv -qL 10
finish_ist () {
cd /root
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo ""
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[1;33m" | pv -qL 10
echo ""
echo -ne "SEU NS: " && cat /root/infons
echo ""
echo -ne "SUA KEY: " && cat /root/server.pub 
echo ""
echo -e "SUA KEY está salva no arquivo /root/server.pub" 
echo ""
echo "PARA REINICIAR O SLOWDNS, BASTA RODAR O COMANDO restartdns" 
echo ""
echo -e "Por segurança, salve os arquivos server.pub e server.key (que estão em /root) em um lugar seguro" 
echo -e "Não será necessário copiar esse arquivo para /root/ nas instalações futuras, mas caso tenha salvo" 
echo -e "Será uma forma de garantir que não terá problemas no futuro!!"
rm -rf dnstt-install
